version: "3.8"
name: "course_planner_services"
services:
  ${SERVICE_NAME}:
    image: "${FINAL_IMAGE_NAME}"
    container_name: "${SERVICE_NAME}"
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    restart: "no"
    expose:
      - "${SERVICE_PORT}"
    environment:
      - POSTGRES_ORDER_PAYMENT_DB_URL=${POSTGRES_ORDER_PAYMENT_DB_URL}
      - POSTGRES_ORDER_PAYMENT_DB_USERNAME=${POSTGRES_ORDER_PAYMENT_DB_USERNAME}
      - POSTGRES_ORDER_PAYMENT_DB_PASSWORD=${POSTGRES_ORDER_PAYMENT_DB_PASSWORD}
      - RP_KEY_ID=${RP_KEY_ID}
      - RP_KEY_SECRET=${RP_KEY_SECRET}