server:
  port: 9005
  servlet:
    context-path: "/api/payment-service"

cp:
  razor-pay:
    key-id: ${RP_KEY_ID:some-key}
    key-secret: ${RP_KEY_SECRET:some-secret}
    enable-logging: false
    payment-link-expiry-minutes: 5
    call-back-url: ""
    notify-email: false
    notify-sms: false

spring:
  datasource:
    url: ${POSTGRES_ORDER_PAYMENT_DB_URL:jdbc:postgresql://localhost:5432/cp_order_payment_db}
    username: ${POSTGRES_ORDER_PAYMENT_DB_USERNAME:cp_service}
    password: ${POSTGRES_ORDER_PAYMENT_DB_PASSWORD:=PM8cT?hO|5BljNJgMr9%+-7(j5.!IgZ}
    driver-class-name: "org.postgresql.Driver"
    hikari:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: "ERROR"
    org.course_planner: "INFO"